import React from 'react';
import { readAssignments } from '../../storage.js';
export default function Dashboard({brand, users=[], currentRole, assignments=[], attendanceStore={}}){
  const students = users.filter(u=> u.role==='Student');
  const today = new Date().toISOString().slice(0,10);
  const todayData = attendanceStore[today]|| {};
  const totalMarked = Object.values(todayData).reduce((sum, arr)=> sum + (arr.filter(r=> r.status==='present').length), 0);
  return (<div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><div className="lg:col-span-2 space-y-4"><div className="p-4 rounded-xl shadow-sm border bg-white"><div className="flex items-center justify-between mb-4"><h2 className="text-lg font-semibold" style={{color:brand.blue}}>Overview</h2><div className="text-sm text-gray-500">Updated just now</div></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><div className="p-3 border rounded-md bg-white"><div className="text-sm text-gray-500">Attendance marked today</div><div className="text-2xl font-bold mt-2" style={{color:brand.blue}}>{totalMarked}</div></div><div className="p-3 border rounded-md bg-white"><div className="text-sm text-gray-500">Homework</div><div className="text-2xl font-bold mt-2" style={{color:brand.blue}}>{readAssignments().length} active</div></div><div className="p-3 border rounded-md bg-white"><div className="text-sm text-gray-500">Fees</div><div className="text-2xl font-bold mt-2">$1,240</div></div></div><div className="mt-4"><h3 className="font-medium text-sm text-gray-700 mb-2">Upcoming</h3><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><div className="p-3 border rounded-md bg-[rgba(12,60,120,0.03)]">School assembly • Apr 28</div><div className="p-3 border rounded-md">Math exam • May 2</div></div></div></div><div className="p-4 rounded-xl shadow-sm border bg-white"><h3 className="text-sm font-semibold mb-3">Recent Announcements</h3><ul className="space-y-2 text-sm text-gray-700"><li>Science fair submissions due Apr 25</li><li>Parent-teacher meeting on May 5</li><li>Bus timings updated</li></ul></div></div><aside className="space-y-4"><div className="p-4 rounded-xl shadow-sm border bg-white"><h4 className="text-sm font-semibold mb-3">Student List</h4><ul className="space-y-2 text-sm text-gray-700">{students.slice(0,4).map((s,idx)=>(<li key={idx} className="flex justify-between"><div><div className="font-medium">{s.name}</div><div className="text-xs text-gray-500">Class: {s.cls || '-'}</div></div><div className={`text-xs text-green-600`}>Active</div></li>))}</ul></div><div className="p-4 rounded-xl shadow-sm border bg-white"><h4 className="text-sm font-semibold mb-3">Quick Actions</h4><div className="flex flex-col gap-2"><button className="px-3 py-2 rounded-md border">Mark Attendance</button><button className="px-3 py-2 rounded-md border text-[rgba(241,90,36,1)]">Create Announcement</button><button className="px-3 py-2 rounded-md border">Add Student</button></div></div></aside></div>);
}
